"""Regression-test generation (Phase 13): a `BUG_VERIFIED` Finding gets a
permanent, executable regression test file written into the *target*
project's own test suite -- not just a `Test` row in VeriForge's database.
Application/target source is never touched; only a new file is added,
under a clearly VeriForge-owned subdirectory.

Keyed by `requirement.id` (Phase 8's *stable*, deterministic id), not
`finding.id` (randomly generated fresh every run) -- one regression test
per logical requirement, regenerated/healed in place across runs, not one
new file accumulating per run for the same bug.

The generated test reuses VeriForge's own Executor+Oracle dispatch
(`execution.experiment_runner.run_experiment`) rather than re-deriving the
HTTP sequence from scratch -- the exact same check that found the bug, run
again, asserting it now PASSES. That means the test currently *fails*
(the bug is still there) and starts passing the moment the application is
fixed; if it starts failing again later, that's a real regression.

Deliberately excludes anything time-varying (a generation timestamp, the
originating Finding/Job id) from the generated source itself: regenerating
from the *same* inputs must produce byte-identical output, or the Test
Healer (healer.py) could never tell "real drift" apart from "cosmetic
re-run noise."
"""
from __future__ import annotations

from pathlib import Path

from veriforge.domain.models import ApiEndpoint, Requirement

_REGRESSION_DIR_NAME = "veriforge_regressions"

_TEMPLATE = '''"""AUTO-GENERATED by VeriForge's Regression Engine (Phase 13).

Do not hand-edit -- regenerate via a fresh `veriforge verify --write-regressions`
run instead; any manual change here will be silently overwritten (or, if it
also changes application behavior on purpose, refused by the Test Healer,
which never touches the assertion below).

Requirement (id={requirement_id!r}): {source_text!r}

This re-runs the exact same check that originally found this requirement
violated, using VeriForge's own Executor/Oracle, and asserts it now PASSES.
That means this test currently FAILS while the underlying bug is still
present, and starts passing once the application is fixed -- if it starts
failing again after that, it's a real regression.

Requires: the `veriforge` package importable, and a server answering at
BASE_URL (override via the VERIFORGE_BASE_URL environment variable) when
this test runs. VeriForge does not start the target application for you.
"""
import os

from veriforge.domain.enums import RequirementKind, Verdict
from veriforge.domain.models import ApiEndpoint, Requirement, Test
from veriforge.execution.experiment_runner import run_experiment
from veriforge.regression.runtime import make_standalone_tool_executor

BASE_URL = os.environ.get("VERIFORGE_BASE_URL", {base_url!r})
DB_PATH = os.environ.get("VERIFORGE_DB_PATH")

_ALL_ENDPOINTS = [
{endpoint_literals}
]
_ACTION_ENDPOINT = _ALL_ENDPOINTS[{action_index}]

_REQUIREMENT = Requirement(
    id={requirement_id!r},
    project_id={project_id!r},
    source_text={source_text!r},
    kind=RequirementKind.{kind_name},
    critical=True,
    structured={structured!r},
)


def test_regression_{safe_requirement_id}():
    executor = make_standalone_tool_executor()
    test = Test(project_id={project_id!r}, name=_REQUIREMENT.source_text)
    try:
        result = run_experiment(
            base_url=BASE_URL,
            requirement=_REQUIREMENT,
            endpoint=_ACTION_ENDPOINT,
            all_endpoints=_ALL_ENDPOINTS,
            tool_executor=executor,
            test=test,
            db_path=DB_PATH,
        )
    finally:
        executor.shutdown()

    assert result.oracle_verdict.verdict == Verdict.PASS, (
        f"Regression: {{_REQUIREMENT.source_text!r}} is violated again -- {{result.oracle_verdict.reasoning}}"
    )
'''


def _endpoint_literal(ep: ApiEndpoint) -> str:
    return (
        f"    ApiEndpoint(project_id={ep.project_id!r}, method={ep.method!r}, path={ep.path!r}, "
        f"source_file={ep.source_file!r}, source_line={ep.source_line!r}, "
        f"mentions_role_check={ep.mentions_role_check!r}),"
    )


def generate_regression_test(
    *,
    requirement: Requirement,
    action_endpoint: ApiEndpoint,
    all_endpoints: list[ApiEndpoint],
    base_url: str,
) -> str:
    if not requirement.structured:
        raise ValueError("cannot generate a regression test for a requirement with no structured invariant")
    try:
        action_index = all_endpoints.index(action_endpoint)
    except ValueError:
        # The action endpoint must itself be one of all_endpoints -- it's
        # the endpoint this exact check was executed against.
        all_endpoints = [*all_endpoints, action_endpoint]
        action_index = len(all_endpoints) - 1

    endpoint_literals = "\n".join(_endpoint_literal(ep) for ep in all_endpoints)
    safe_requirement_id = requirement.id.replace("-", "_")

    return _TEMPLATE.format(
        requirement_id=requirement.id,
        safe_requirement_id=safe_requirement_id,
        source_text=requirement.source_text,
        project_id=requirement.project_id,
        kind_name=requirement.kind.name,
        structured=requirement.structured,
        base_url=base_url,
        endpoint_literals=endpoint_literals,
        action_index=action_index,
    )


def regression_dir(repo_path: str) -> Path:
    return Path(repo_path) / _REGRESSION_DIR_NAME


def regression_test_path(repo_path: str, requirement: Requirement) -> Path:
    return regression_dir(repo_path) / f"test_regression_{requirement.id}.py"


def write_regression_test(
    *,
    repo_path: str,
    requirement: Requirement,
    action_endpoint: ApiEndpoint,
    all_endpoints: list[ApiEndpoint],
    base_url: str,
) -> Path:
    """Writes (or overwrites) the regression test file for `requirement`.
    Callers that want drift detected instead of silently overwritten
    should compare against the existing file via healer.heal_regression_test
    before calling this."""
    source = generate_regression_test(
        requirement=requirement, action_endpoint=action_endpoint,
        all_endpoints=all_endpoints, base_url=base_url,
    )
    target_dir = regression_dir(repo_path)
    target_dir.mkdir(parents=True, exist_ok=True)
    init_file = target_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("", encoding="utf-8")
    path = regression_test_path(repo_path, requirement)
    path.write_text(source, encoding="utf-8")
    return path
