"""CI/GitHub PR integration (Phase 20): turns a real job's `RunSummary` +
`Finding`s into the exact markdown a CI pipeline would post as a PR
comment, and — given an explicit token — posts it via GitHub's real REST
API.

Scoped the same way Phase 17 scoped GitHub access: a token the caller
explicitly provides (`VERIFORGE_GITHUB_TOKEN`), never an OAuth/App
installation flow (see `source/github.py`'s own reasoning — no App
registration exists to build or test that against honestly).

`post_pr_comment` posting a comment is a real, visible, hard-to-undo
action on someone else's pull request. Nothing in this codebase calls it
automatically — a caller (a CI workflow, or a human explicitly passing
`--post-pr` to the CLI) invokes it deliberately, once, with an explicit
repo/PR/token. It has never been run against a real PR in this project's
own development; only `format_pr_comment` (a pure function) and a mocked
HTTP layer have been exercised, which is the honest state to leave it in
until a real CI workflow actually calls it.
"""
from __future__ import annotations

import re

import httpx

from veriforge.domain.enums import Verdict
from veriforge.domain.models import Finding

_PR_SLUG_RE = re.compile(r"^(?P<owner>[\w.-]+)/(?P<repo>[\w.-]+)#(?P<number>\d+)$")


class InvalidPrTargetError(ValueError):
    pass


def parse_pr_target(target: str) -> tuple[str, str, int]:
    """"owner/repo#123" -> ("owner", "repo", 123)."""
    match = _PR_SLUG_RE.match(target.strip())
    if not match:
        raise InvalidPrTargetError(f"expected 'owner/repo#123', got {target!r}")
    return match.group("owner"), match.group("repo"), int(match.group("number"))


def format_pr_comment(*, job_id: str, repo_display: str, verdict: str | None, findings: list[Finding]) -> str:
    lines = [f"### VeriForge verification — `{repo_display}`", ""]

    if verdict is None:
        lines.append("_No executable requirement was found to check on this run._")
    elif verdict == Verdict.PASS.value:
        lines.append("✅ **PASS** — the checked requirement was satisfied.")
    elif verdict == Verdict.FAIL.value:
        lines.append("❌ **FAIL** — a requirement violation was confirmed.")
    else:
        lines.append("⚠️ **UNCERTAIN** — the result was not decisive.")

    if findings:
        lines.append("")
        lines.append("**Findings:**")
        for f in findings:
            reproduced_note = " _(reproduced on a second run)_" if f.reproduced else ""
            lines.append(f"- `{f.category.value}` (confidence {f.confidence:.2f}){reproduced_note}: {f.summary}")

    lines.append("")
    lines.append(f"<sub>Job `{job_id}` — generated by VeriForge. Application source is never modified.</sub>")
    return "\n".join(lines)


def post_pr_comment(*, owner: str, repo: str, pr_number: int, body: str, token: str) -> None:
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    resp = httpx.post(url, headers=headers, json={"body": body}, timeout=15.0)
    resp.raise_for_status()
